version: '3'

services:
  postgresql:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: readify
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:6.8.0
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:6.8.0
    ports:
      - "5601:5601"