# curl --location --request POST 'localhost:8080/v1/users/'
#--header 'Content-Type: application/json'
#--data-raw '{
#  "username": "mpp00017",
#  "email" : "mpp00017@gmail.com",
#  "password": "123456"
#}'
POST localhost:8000/v1/users
Content-Type: application/json

{
  "username": "mpp00017",
  "email" : "mpp00017@gmail.com",
  "password": "123456"
}

###